use super::{
    BLOSSOM_ACTIVATION, POST_BLOSSOM_HALVING_INTERVAL, PRE_BLOSSOM_HALVING_INTERVAL,
    SUBSIDY_SLOW_START_INTERVAL, SUBSIDY_SLOW_START_SHIFT,
};
use crate::units::Height;
use test_case::test_case;

const FIRST_HALVING: Height = 1_046_400;
const SECOND_HALVING: Height = FIRST_HALVING + POST_BLOSSOM_HALVING_INTERVAL;

// Define boundary values around constants:
const FIRST_HALVING_MINUS_1: Height = FIRST_HALVING - 1;
const FIRST_HALVING_PLUS_1: Height = FIRST_HALVING + 1;

const SECOND_HALVING_MINUS_1: Height = SECOND_HALVING - 1;
const SECOND_HALVING_PLUS_1: Height = SECOND_HALVING + 1;

const SUBSIDY_SLOW_START_SHIFT_MINUS_1: Height = SUBSIDY_SLOW_START_SHIFT - 1;
const SUBSIDY_SLOW_START_SHIFT_PLUS_1: Height = SUBSIDY_SLOW_START_SHIFT + 1;

const SUBSIDY_SLOW_START_INTERVAL_MINUS_1: Height = SUBSIDY_SLOW_START_INTERVAL - 1;
const SUBSIDY_SLOW_START_INTERVAL_PLUS_1: Height = SUBSIDY_SLOW_START_INTERVAL + 1;

const BLOSSOM_ACTIVATION_MINUS_1: Height = BLOSSOM_ACTIVATION - 1;
const BLOSSOM_ACTIVATION_PLUS_1: Height = BLOSSOM_ACTIVATION + 1;

const PRE_BLOSSOM_HALVING_INTERVAL_MINUS_1: Height = PRE_BLOSSOM_HALVING_INTERVAL - 1;
const PRE_BLOSSOM_HALVING_INTERVAL_PLUS_1: Height = PRE_BLOSSOM_HALVING_INTERVAL + 1;

const POST_BLOSSOM_HALVING_INTERVAL_MINUS_1: Height = POST_BLOSSOM_HALVING_INTERVAL - 1;
const POST_BLOSSOM_HALVING_INTERVAL_PLUS_1: Height = POST_BLOSSOM_HALVING_INTERVAL + 1;

#[test_case(0 => 0)]
#[test_case(1 => 0)]
#[test_case(SUBSIDY_SLOW_START_SHIFT => 0)]
#[test_case(SUBSIDY_SLOW_START_SHIFT_MINUS_1 => 0)]
#[test_case(SUBSIDY_SLOW_START_SHIFT_PLUS_1 => 0)]
#[test_case(SUBSIDY_SLOW_START_INTERVAL => 0)]
#[test_case(SUBSIDY_SLOW_START_INTERVAL_MINUS_1 => 0)]
#[test_case(SUBSIDY_SLOW_START_INTERVAL_PLUS_1 => 0)]
#[test_case(BLOSSOM_ACTIVATION => 0)]
#[test_case(BLOSSOM_ACTIVATION_MINUS_1 => 0)]
#[test_case(BLOSSOM_ACTIVATION_PLUS_1 => 0)]
#[test_case(PRE_BLOSSOM_HALVING_INTERVAL => 0)]
#[test_case(PRE_BLOSSOM_HALVING_INTERVAL_MINUS_1 => 0)]
#[test_case(PRE_BLOSSOM_HALVING_INTERVAL_PLUS_1 => 0)]
#[test_case(POST_BLOSSOM_HALVING_INTERVAL => 1)]
#[test_case(POST_BLOSSOM_HALVING_INTERVAL_MINUS_1 => 1)]
#[test_case(POST_BLOSSOM_HALVING_INTERVAL_PLUS_1 => 1)]
#[test_case(FIRST_HALVING => 1)]
#[test_case(FIRST_HALVING_MINUS_1 => 0)]
#[test_case(FIRST_HALVING_PLUS_1 => 1)]
#[test_case(SECOND_HALVING => 2)]
#[test_case(SECOND_HALVING_MINUS_1 => 1)]
#[test_case(SECOND_HALVING_PLUS_1 => 2)]
fn halvings_at(height: Height) -> usize {
    super::halvings_at(height)
}
